name: continuous integration

on: [push]

jobs:
  general:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          
      - name: lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy

      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: test library
        uses: actions-rs/cargo@v1
        with: 
          command: test
          args: -- --nocapture
        